# Generated by Django 4.2 on 2023-05-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='bill_amount',
        ),
    ]
