# Generated by Django 4.2 on 2023-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_timestamp_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
